AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      LoggingConfiguration:
        DestinationBucketName: !ImportValue LoggingBucket
      VersioningConfiguration:
        Status: Enabled
Outputs:
  BucketName:
    Value: !Ref 'ArtifactBucket'
    Description: Name of the artifact bucket.
    Export:
      Name: ArtifactBucket