AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ -, [ 'artifacts', !Ref 'AWS::Region', !Ref 'AWS::AccountId' ]]
      AccessControl: Private
      LoggingConfiguration:
        DestinationBucketName: !ImportValue LoggingBucket
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - Id: ExpireRule
          Status: Enabled
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: 7
Outputs:
  BucketName:
    Value: !Ref 'ArtifactBucket'
    Description: Name of the artifact bucket.
    Export:
      Name: ArtifactBucket